{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(rate(totalPurchases_total[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "round(rate(failedPurchases_total[1m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Computer Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "diskUsage_percent", "legendFormat": "Disk Usage" },
    { "expr": "cpuUsage_percent", "legendFormat": "CPU Usage" },
    { "expr": "memoryUsage_percent", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "averageResponseTime_milliseconds",
     "legendFormat": "Average Request Latency"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "round(rate(successfulAuths_total[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "round(rate(failedAuths_total[1m])*60)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 7, "y": 15 },
   "targets": [
    { "expr": "rate(postRequests_total[1m])", "legendFormat": "Post Requests" },
    { "expr": "rate(getRequests_total[1m])", "legendFormat": "Get Requests" },
    { "expr": "rate(putRequests_total[1m])", "legendFormat": "Put Requests" },
    { "expr": "rate(deleteRequests_total[1m])", "legendFormat": "Delete Requests" },
    { "expr": "rate(totalRequests_total[1m])", "legendFormat": "All Requests" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "pizzaCreationTime_milliseconds", "legendFormat": "Pizza Latency" }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "targets": [
    { "expr": "activeUsers_ratio", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "totalProfits_total", "legendFormat": "Revenue" }
   ]
  }
 ]
}